import Head from "next/head";
import React from "react";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home({}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Zikoat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Zikoat makes games</h1>
        <p>🚧 site under construction</p>
        <p className={styles.description}>
          <Link href={"/dashpaint"}>Dashpaint</Link>
        </p>
        <p className={styles.description}>
          <Link href={"/minesweeper"}>Minesweeper (under construction)</Link>
        </p>
      </main>
    </div>
  );
}
